services:
  frontend:
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: npm run dev
    environment:
      - VITE_API_URL=http://localhost:4000
      - NODE_ENV=development

  backend:
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
