version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: sh -c "npm run migrate:up && npm start"
    ports:
      - "4000:4000"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_HOST=mongo
      - MONGO_PORT=${MONGO_PORT}  # 新增端口变量
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    pull_policy: if_not_present
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: