services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000
      - VITE_API_URL=http://backend:4000
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - NODE_ENV=${NODE_ENV}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  mongo:
    container_name: mongo
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  frontend_node_modules:
  backend_node_modules:
